import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import {ClerkProvider} from '@clerk/nextjs'
import { Toaster } from "sonner";
import NProgress from 'nprogress'
import NProgressProvider from "./_components/NProgressProvider";
import { ThemeProvider } from "./_components/ThemeProvider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
<ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
   <ThemeProvider
    attribute={"class"}
     defaultTheme="system"
     enableSystem
   >
         <TRPCReactProvider>{children}</TRPCReactProvider>
        <Toaster richColors/>
        <NProgressProvider/>
   </ThemeProvider>
      </body>
    </html>
</ClerkProvider>
  );
}
